import tweepy
import random  # just in case if you want a random number of likes/retweets you want to execute for automation
import time


# Enter the credentials generated by your Twitter API
consumer_key = input("Enter Consumer Key: ")
consumer_secret = input("Enter Consumer Key Secret: ")
access_token = input("Enter Access Token: ")
access_token_secret = input("Enter Token Secret: ")

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

user = api.me()


# Printing account owner's name
print('You are\t' + user.screen_name)

# Printing the names of latest people who follow you
# print("Your latest followers' usernames: \n")
# for follower in api.followers(user.screen_name):
#     print(follower.screen_name)


n = int(input("Enter\n 1. for auto-likes\n 2. for auto-retweet\n 3. for auto-follow-back: \n"))


if n == 1:
    search = (input("Enter the hashtag to execute your automation : "))
    nTweets = int(
        input("Enter the number of tweets you want for your automation: "))
    auth = tweepy.OAuthHandler(consumer_key,
                               consumer_secret)
    auth.set_access_token(access_token,
                          access_token_secret)

    api = tweepy.API(auth, wait_on_rate_limit=True,
                     wait_on_rate_limit_notify=True)

    user = api.me()

    for tweet in tweepy.Cursor(api.search, search).items(nTweets):
        try:
            print('You liked a tweet!')

        # putting a time-pause to avoid any breaking of rules of hit-limit; feel free to change/remove it
            time.sleep(3)

            tweet.favorite()

        except tweepy.TweepError as e:
            print(e.reason)
        except StopIteration:
            break

elif n == 2:
    search = (input("Enter the hashtag to execute your automation : "))
    nTweets = int(
        input("Enter the number of tweets you want for your automation: "))

    for tweet in tweepy.Cursor(api.search, search).items(nTweets):
        try:
            tweet.retweet()

            # putting a time-pause to avoid any breaking of rules of hit-limit; feel free to change/remove it
            time.sleep(3)

            print("Tweet Retweeted!")
        except tweepy.TweepError as e:
            print(e.reason)
        except StopIteration:
            break

elif n == 3:
    followers = tweepy.Cursor(api.followers).items()

    for follower in followers:
        num = random.randint(0, 100)
        if num == 20:  # put any number of your choice, depending on the no. of people you want to follow back
            follower.follow()
            print('You just followed ' + follower.screen_name + '!')
