import tweepy
import time


# Enter the credentials generated by your Twitter API
consumer_key = input("Enter Consumer Key: ")
consumer_secret = input("Enter Consumer Key Secret: ")
access_token = input("ENter Access Token: ")
access_token_secret = input("Enter Token Secret: ")

# authorization of consumer key and consumer secret
auth = tweepy.OAuthHandler(consumer_key,
                           consumer_secret)

# setting access to user's access key and access secret
auth.set_access_token(access_token,
                      access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True,
                 wait_on_rate_limit_notify=True)


user = api.me()  # mines the data of any user


# Printing owner's name
print('You are ' + user.screen_name)


# Printing the names of latest people who follow you
print("Your latest followers' usernames: \n")
for follower in api.followers(user.screen_name):
    print(follower.screen_name)

# Providing particular hashtag to auto-like
search = input('Enter hashtag to execute automation: ')
nTweets = int(
    input("Enter the number of tweets you want for your automation: "))

for tweet in tweepy.Cursor(api.search, search).items(nTweets):
    try:
        print('You liked a tweet!')
        # putting a time-pause to avoid any breaking of rules of hit-limit; feel free to change/remove it
        time.sleep(3)
        tweet.favorite()

    except tweepy.TweepError as e:
        print(e.reason)
    except StopIteration:
        break
