import tweepy
import random

# Enter the credentials generated by your Twitter API
consumer_key = input("Enter Consumer Key: ")
consumer_secret = input("Enter Consumer Key Secret: ")
access_token = input("ENter Access Token: ")
access_token_secret = input("Enter Token Secret: ")

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)


user = api.me()

# Printing the names of latest people who follow you
print("Your latest followers' usernames: ")
for follower in api.followers(user.screen_name):
    print(follower.screen_name)


followers = tweepy.Cursor(api.followers).items()

for follower in followers:
    num = random.randint(0, 9)
    if num == 20:  # put any number of your choice, depending on the no. of people you want to follow back
        follower.follow()
        print('You just followed ' + follower.screen_name + '!')
