import tweepy
import random
import time

# Enter the credentials generated by your Twitter API
consumer_key = input("Enter Consumer Key: ")
consumer_secret = input("Enter Consumer Key Secret: ")
access_token = input("ENter Access Token: ")
access_token_secret = input("Enter Token Secret: ")


auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

user = api.me()
# print(user.name)


def main():

    # hashtags you'd like for the reference of retweeting
    search = input(('Enter hashtag to execute automation:  '))

    # numberofTweets = random.randint(20, 200)
    # print(numberofTweets)

    numberofTweets = int(
        input("Enter the number of tweets you want for your automation: "))  # put the number of retweets you want to execute

    for tweet in tweepy.Cursor(api.search, search).items(numberofTweets):
        try:
            tweet.retweet()

            # putting a time-pause to avoid any breaking of rules of hit-limit; feel free to change/remove it
            time.sleep(3)

            print("Tweet Retweeted!")
        except tweepy.TweepError as e:
            print(e.reason)
        except StopIteration:
            break


main()
